sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: wKKBegzjcnR+SFaz/obozH9TkS/W7EJSb+CYO9UTQszFmtMv8SO92peeQtmgdBYLPDMorhoJCMO0dEA0TM7o7Xft5U4gpFpr51JW5z7fPuIzFH4VVffcXXLXhoN65ktUgHOGcZJVEUcs/psIn0Sli/BfdC6npivZb7HSrA1lwh61zn7tzYGnpxcvCk4aeSSwmak+OR9Du0aYHIifeysWG6xIZwoIi/LbT/FfjqquYtOuoD1B8qfN8TAL+13HH26ty4Es43rsnRiwit3sMRMbknWIgR62WY//GmQM2UkwDc4Dmnhnr9l/mbtpCXLc5TwRI5P+JI8bQMIwxu7aR0qrmCEO5dwmvJZxz9J4MPcCRMAP232J/62PJ64TxEcrfIfvl/S8p7wu4M6l/lykawK/xRQLIDa6ZTXsXOy83vyRnxONvICfSLYm7gJ20VNb+Qo2l0lFv2u+c25zo51VR0gm9dsWfcWYNfBz1Fi0ZVidkoYfAywJc5arssQ4XaLgJ3crV+OjtQF1uCQQUUFyx/qEj7p7O1RIiMC+O/m2YqnY3mxA8fQo0oqUXw+4I33bnvfYgR6sEm6oem9Dxz6KkpxzjIRrZ2bbH4nfMNkfgRyAFcYyGSd5IPUVnQ7LaSHuz24PXfDKlCcehQ720vnBeRYdv6Tsci1mp4V+A2vEFhNciuw=
  app: dukeapolandingpage
  on:
    repo: DukeAPO/landing-page
